#! /bin/bash

nasm -f elf64 -I ../include/ -g -o test.o $1
nasm -f elf64 -g -o lib.o ../lib.asm
ld lib.o test.o -o test
shift
./test "$@"
echo -e "\nexit_code:" $?
rm -rf test.o
rm -rf lib.o
rm -rf test
